### ISSUE TITLE
Additional fields feedback

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#20]
From the scoping document:

"As a publisher, I need to get feedback on whether my data includes additional fields so that I can correct errors."

A table of fields that are not part of the RDLS schema with examples of the values of each additional field.

**Comment by duncandewhurst** [comment]
* Can we implement the same columns as shown in the scoping document?

![image](https://github.com/GFDRR/rdls-cove/assets/19265814/71dc1c3e-7948-4ed0-a3e6-4306f0690df5)

* Replace the '!' at the end of 'There were no additional fields' with a period.

**Comment by duncandewhurst** [comment]
![Image](https://github.com/GFDRR/rdls-cove/assets/19265814/d67250c6-5252-4a25-818a-24a52a085aaa)

**Comment by duncandewhurst** [comment]
Field Name -> Field name
Contents -> First 3 examples
Where field occurs -> Location

Make formatting in first 3 examples column consistent with formatting in first 3 examples column in validation errors table

**Comment by duncandewhurst** [comment]
[Test data](https://github.com/GFDRR/rdls-cove/raw/test_data/test_data/additional_fields.json)

**Comment by radix0000** [comment]
Updated.

**Comment by duncandewhurst** [comment]
I'm assuming that we're supposed to be testing the version deployed to https://metadata.riskdatalibrary.org/ now since http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/ returns an error.

However, due to https://github.com/GFDRR/rdls-cove/issues/29 I can't get to the results screen to check the updates.

@odscrachel once that issue is resolved, please can you test using the test data in https://github.com/GFDRR/rdls-cove/issues/20#issuecomment-1706290072

**Comment by odscrachel** [comment]
![Screenshot from 2023-09-08 11-30-11](https://github.com/GFDRR/rdls-cove/assets/59564404/a3a7fb70-6097-4a40-b104-b4a4082714a6)

This has been updated and changed, do you want to double check you're happy with the column names @duncandewhurst 
The capitalising the second word is consistent with the rest of tool and scoping, so I'm happy with this.

**Comment by duncandewhurst** [comment]
Feature looks good to me :+1:
