### ISSUE TITLE
Landing page copy

### ISSUE THREAD

**Issue by odscjen** [GFDRR/rdls-cove#21]
From the scoping document:

"As a publisher, I need information on how to use the tool and how it relates to the spreadsheet template and RDLS."

Text that describes how to use the tool, how it relates to RDLS and how it relates to the spreadsheet template.

**Comment by odscjen** [comment]
# About the Risk Data Library Standard

The Risk Data Library Standard (RDLS) is an open data standard to make it easier to work with disaster and climate risk data. It provides a common description of the data used and produced in risk assessments, including hazard, exposure, vulnerability, and modelled loss, or impact, data.

The RDLS provides a unique way to create, store, exchange and use disaster different risk information together. It is at the core of the Risk Data Library, a suite of open-source tools to work with disaster and climate risk data.

Learn more at the [RDLS documentation website](https://rdl-standard.readthedocs.io/en/latest/).


# Checking and reviewing your data

After submitting your data you will be presented with the results of your data review:

    Download data. A chance to save your data in an alternative format.
    Validation errors. A list of standard JSON validation errors.
    Additional fields. If your data contains unrecognised fields, they will be listed.
    Statistics. A breakdown of the make-up of your data and indicators of its quality.

Amend your data to address errors and problems, or to improve its quality.

# Using the data review tool

Use one of the links below to check that your data complies with the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (RDLS).

    Upload a RDLS metadata file;
    Link to RDLS metadata on the web using a URL; or
    Paste in your RDLS JSON metadata

After submitting your metadata, use the information provided on the Results page to [check and review](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) the data’s quality and compliance with RDLS. Your data can also be downloaded in alternative RDLS-compliant formats from the Results page.
Accepted RDLS formats

    JSON built to the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (UTF-8 encoding supported)
    Multi-table data package - Excel (.xlsx) (UTF-8, Windows-1252 and ISO-8859-1 encodings supported)

## Large datasets

If your data file is larger than 10MB, this analysis may take some time. You can process a subset of your submitted data using Sample mode (see below). Alternatively you can install our [data review library](https://pypi.org/project/libcoverdls/) to analyse files via your command line interface.

Sample mode validates and analyses the data from a subset of the submitted RDLS datasets. Datasets of all four types (hazard, exposure, vulnerability and loss) are represented in the sample. Sampling is not random: if an unchanging data is run through the data review tool multiple times, the same datasets will form the sample each time. Conformance tests that require processing of the complete data are not run in Sample mode.

## Feedback and support

Submit feedback, issues or bugs via [the rdls-cove repository](https://github.com/GFDRR/rdls-cove/). For further information or support email [contact@riskdatalibrary.org](mailto:contact@riskdatalibrary.org).

**Comment by stufraser1** [comment]
Some Spanish text remains:
"Uso de la herramienta de revisión de datos
Use one of the links below to check that your data complies with the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (RDLS)."

And 

"About

    Construido por [Open Data Services](http://opendataservices.coop/)
    El código de este sitio está disponible en
    GitHub: [rdls-cove](https://github.com/GFDRR/rdls-cove/)
    Licencia: [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html)
    Reportar / Ver issues: [rdls-cove issues](https://github.com/GFDRR/rdls-cove/issues)

    [Terms & Conditions](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/terms/)

Versión en ejecución[763d45b](https://github.com/GFDRR/rdls-cove/tree/763d45b)"

**Comment by stufraser1** [comment]
instructions
"Upload a RDLS metadata file;
Link to RDLS metadata on the web using a URL; "
are not clear what file formats are accepted - can this be made clearer?

**Comment by stufraser1** [comment]
"After submitting your metadata, use the information provided on the Results page to [check and review](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) the data’s quality and compliance with RDLS. Your data can also be downloaded in alternative RDLS-compliant formats from the Results page."

Does not reference the fact that an RDLS-compliant JSON file is created when you click 'submit' button.

**Comment by odscrachel** [comment]
# About the Risk Data Library Standard
 
 The Risk Data Library Standard (RDLS) is an open data standard to make it easier to work with disaster and climate risk data. It provides a common description of the data used and produced in risk assessments, including hazard, exposure, vulnerability, and modelled loss, or impact, data.
 
 The RDLS provides a unique way to create, store, exchange and use disaster different risk information together. It is at the core of the Risk Data Library, a suite of open-source tools to work with disaster and climate risk data.
 
 Learn more at the [RDLS documentation website](https://rdl-standard.readthedocs.io/en/latest/).
 # Checking and reviewing your data
 
 After submitting your data you will be presented with the results of your data review:
 
 ```
 Download data. A chance to save your data in an alternative format.
 Validation errors. A list of standard JSON validation errors.
 Additional fields. If your data contains unrecognised fields, they will be listed.
 Statistics. A breakdown of the make-up of your data and indicators of its quality.
 ```
 
 Amend your data to address errors and problems, or to improve its quality.
 # Using the data review tool
 
 Use one of the links below to check that your data complies with the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (RDLS).
 
 ```
 Upload a RDLS metadata file (JSON or XLSX);
 Link to RDLS metadata on the web using a URL; or
 Paste in your RDLS JSON metadata
 ```
 
 After submitting your metadata, use the information provided on the Results page to [check and review](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) the data’s quality and compliance with RDLS. 

You can also submit your data to convert it in to alternative RDLS-compliant formats (i.e. from XLSX to JSON). This can be downloaded under the heading: 'Download Data'.

## Accepted RDLS formats
 
 ```
 JSON built to the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (UTF-8 encoding supported)
 Multi-table data package - Excel (.xlsx) (UTF-8, Windows-1252 and ISO-8859-1 encodings supported)
 ```
 
 ## Feedback and support
 
Submit feedback, issues or bugs via [the rdls-cove repository](https://github.com/GFDRR/rdls-cove/). For further information or support email [contact@riskdatalibrary.org](mailto:contact@riskdatalibrary.org).

**Comment by odscrachel** [comment]
Hi @stufraser1 could you review the copy including your suggested changes. I've also removed the large dataset/sampling section as this is unnecessary.

**Comment by stufraser1** [comment]
Thanks.
Most looks great.

Can you clarify 
1. 'Link to RDLS metadata on the web using a URL' - is a link to a json file / xlsx spreadsheet template?
2. 'JSON built to the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (UTF-8 encoding supported)' - should this link be to .../schema.json?
3. 'Multi-table data package - Excel (.xlsx) (UTF-8, Windows-1252 and ISO-8859-1 encodings supported)' - should this refer to the spreadsheet template explictly?

**Comment by odscrachel** [comment]
> Thanks. Most looks great.
> 
> Can you clarify
> 
>    'Link to RDLS metadata on the web using a URL' - is a link to a json file / xlsx spreadsheet template?

This allows for a link to be submitted from data published online, you can see an example [here](https://dati.anticorruzione.it/opendata/download/dataset/ocds/filesystem/bulk/2019/05.json) from another standard. 
> 
>    'JSON built to the [Risk Data Library Standard](http://rdsl-cove-dev-main.dokkurdlsdev1.ods.mobi/#introduction) (UTF-8 encoding supported)' - should this link be to .../schema.json?

Or perhaps the docs reference page might be more helpful here?

> 
>    'Multi-table data package - Excel (.xlsx) (UTF-8, Windows-1252 and ISO-8859-1 encodings supported)' - should this refer to the spreadsheet template explictly?

We could mention it here but I think technically we're just being clear what encodings of xlsx are acceptable

**Comment by duncandewhurst** [comment]
I'm suggesting a few changes below:

* Align language with title of the tool ("convert and validate")
* Align the about section with the introductory text on the [documentation landing page on the `dev` branch](https://docs.riskdatalibrary.org/en/dev/) (the current version looks to be based on the old text from the `main` branch).
* Update links to use the new documentation URL (https://docs.riskdatalibrary.org)
* Refer to metadata rather than data
* Add data retention notice (@radix0000 please check this is correct)
* Use active voice
* Reference the RDLS spreadsheet template (since the spreadsheet format is not otherwise defined anywhere and we want to avoid implementers trying to create spreadsheet data from scratch)
* Reference the RDLS package schema (since that defines the necessary format for JSON data)
* Link to the guidance on preparing RDLS metadata
* General copy-editing

---

# Convert and validate your RDLS metadata

Use the form below to submit your RDLS metadata for conversion and validation against the RDLS schema. 

You can submit metadata in the following formats:

* **Spreadsheet format**: a completed [RDLS spreadsheet template](https://github.com/GFDRR/rdls-spreadsheet-template/) in XLSX format.
* **JSON format**: A UTF-8 encoded JSON file that conforms to the [RDLS package schema](https://docs.riskdatalibrary.org/en/dev/reference/package_schema/).

For more information on how to prepare RDLS metadata, read the [guidance](https://docs.riskdatalibrary.org/en/dev/guides/metadata/#prepare-your-metadata).

You can submit metadata in the above formats by uploading it from your local machine, providing a link to a publicly-accessible URL or pasting it from your clipboard (JSON format only).

After submitting your metadata, you can download it in alternative formats and get feedback on its quality. The RDLS Convertor stores your metadata for 90 days at a randomly generated URL. You can share the URL with others to support discussion of data quality.

## Support and feedback

Need help with publishing RDLS metadata? Contact a member of the Risk Data Library team: [contact@riskdatalibrary.org](mailto:contact@riskdatalibrary.org)

To submit feedback on the RDLS Convertor or to report a bug, [open a GitHub issue](https://github.com/GFDRR/rdls-cove/issues/new/choose).

# About the Risk Data Library Standard
 
The [Risk Data Library Standard (RDLS)](https://docs.riskdatalibrary.org) is an open metadata standard for describing risk datasets used in climate and disaster risk assessments.

The purpose of the RDLS is to enable risk reduction and resilience building by making it easier for risk data publishers to describe their datasets and for risk data users to identify datasets to use in their work. 
 
For more information about the RDLS, [read its documentation](https://docs.riskdatalibrary.org).

# Getting feedback on your metadata

The RDLS Convertor validates your metadata against the [RDLS schema](https://docs.riskdatalibrary.org/en/dev/reference/schema/) and provides feedback on its structure and format. The convertor reports validation errors including missing required fields and fields with incorrect types or formats. It also reports any additional fields in your metadata that are not specified in the RDLS schema.

You should use the guidance provided by the RDLS Convertor to fix the issues with your metadata. To support further review, you can download your data in alternative formats.

**Comment by radix0000** [comment]
New copy is up. Please check and report anything you spot, otherwise will close tomorrow.

**Comment by duncandewhurst** [comment]
![feedback](https://github.com/GFDRR/rdls-cove/assets/19265814/51d19729-42be-4a72-b678-055d56901413)

**Comment by radix0000** [comment]
Updated.

**Comment by duncandewhurst** [comment]
The "You can submit metadata in the following formats:" sentence from https://github.com/GFDRR/rdls-cove/issues/21#issuecomment-1705727975 is missing. It should appear before the bullet points describing the supported formats.

**Comment by duncandewhurst** [comment]
> The "You can submit metadata in the following formats:" sentence from [#21 (comment)](https://github.com/GFDRR/rdls-cove/issues/21#issuecomment-1705727975) is missing. It should appear before the bullet points describing the supported formats.

This is now fixed.
