### ISSUE TITLE
Stuck on 'your data is queued for processing' 

### ISSUE THREAD

**Issue by johcarter** [GFDRR/rdls-cove#30]
Hello

I'm seeing this issue today.  
https://github.com/GFDRR/rdls-cove/issues/29

I waited about 20 mins, then resubmitted the file and i'm waiting again now.

It was working fine earlier today. I've used it about 10-20 times.

**Comment by radix0000** [comment]
We can't reproduce the problem so it could either be transitory issue that is gone now, or is some how related to your specific data. If you could try again and let us know if it is working for you now, that would be great. Otherwise we would need a copy of the file you uploaded in order to investigate further. Thanks.

**Comment by johcarter** [comment]
I tried it again today and it worked immediately. closing issue - thanks
